plugins {
    id 'idea'
    id 'maven-publish'
    alias libs.plugins.fabric.loom
}

def ENV = System.getenv()
def buildTime = ENV.BUILD_TIME ?: new Date().format("yyyyMMddHHmmss")

def javaVersion = 17

group = project.maven_group

boolean isPreviewBuild = !ENV.TAG || ENV.TAG.matches(".+-.+")
def buildNumber = !ENV.TAG ? ("${ENV.BUILD_NUMBER ? "build.${ENV.BUILD_NUMBER}" : buildTime}-${libs.versions.minecraft.get()}") : ""
version = (ENV.TAG ?: "development") + ((isPreviewBuild && !ENV.TAG) ? "+${buildNumber}" : "")

base {
    archivesName.set(project.mod_id)
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.terraformersmc.com' }
    maven { url = 'https://maven.uuid.gg/releases' }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
        content {
            includeGroupAndSubgroups('org.parchmentmc')
        }
    }
    exclusiveContent {
        forRepository {
            maven { url "https://api.modrinth.com/maven" }
        }
        filter {
            includeGroup("maven.modrinth")
        }
    }

}

dependencies {
    minecraft libs.minecraft
    mappings(loom.layered {
        it.officialMojangMappings()
        it.parchment("org.parchmentmc.data:parchment-${libs.versions.parchment.minecraft.get()}:${libs.versions.parchment.mappings.get()}@zip")
    })

    modImplementation libs.fabric.loader
    modImplementation libs.fabric.api

    modCompileOnly libs.modmenu
    modLocalRuntime libs.modmenu

    modLocalRuntime libs.emi
}

processResources {
    inputs.property "version", project.version

    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile) {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    options.encoding = "UTF-8"

    options.release.set(javaVersion)
}

java {
    withSourcesJar()

    toolchain {
        languageVersion.set(JavaLanguageVersion.of(javaVersion))
        vendor = JvmVendorSpec.MICROSOFT
    }
}

jar {
    from(layout.projectDirectory) {
        include "LICENSE"
        rename { "LICENSE_${project.mod_id}" }
    }

    manifest.mainAttributes(
            "Implementation-Title": project.mod_id,
            "Implementation-Version": project.version,
            "Maven-Artifact": "${project.group}:${rootProject.name}-Fabric:${project.version}",
            "Built-On-Minecraft": libs.versions.minecraft.get(),
            "Built-On-Java": "${System.getProperty("java.vm.version")} (${System.getProperty("java.vm.vendor")})"
    )
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId "${rootProject.name}-Fabric"
            from components.java
        }
    }

    repositories {
        if (ENV.MAVEN_UPLOAD_URL) {
            maven {
                url = ENV.MAVEN_UPLOAD_URL
                credentials {
                    username = ENV.MAVEN_UPLOAD_USERNAME
                    password = ENV.MAVEN_UPLOAD_PASSWORD
                }
            }
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
