# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Metadata
mod_id=hookshot
mod_description=Just a simple mod that adds a Hookshot into the game.
mod_display_name=Hookshot
sources_url=https://github.com/CammiePone/Hookshot
issues_url=https://github.com/CammiePone/Hookshot/issues
license_url=https://github.com/CammiePone/Hookshot/blob/HEAD/LICENSE.md
discord_url=https://mods.upcraft.dev/discord
homepage_url=https://www.curseforge.com/projects/396512
maven_group_id=dev.cammiescorner.hookshot

# Dependencies are managed at gradle/libs.versions.toml
