# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Versions
minecraft_version=1.21.1
neo_version=21.1.233

# Mod metadata
mod_id=hookshot
mod_version=1.21.1-port-1.0.0
mod_display_name=Hookshot
mod_description=Just a simple mod that adds a Hookshot into the game. Unofficial NeoForge 1.21.1 port.
maven_group_id=dev.cammiescorner.hookshot
